config/routes.rb
Rails.application.routes.draw do
  resources :events
  namespace :management, :path => 'acesso' do

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :departments, :path => 'departamentos'
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :users, :path => "usuarios"
    end

    scope(:path_names => {:edit => "visualizar" }) do
      resources :solicitations, :path => 'solicitacoes'  do
        collection do
          put "aprovar/:id", :as => "approve", :action => "approve"
          put "recusar/:id", :as => "refuse", :action => "refuse"
          put "cancelar/:id", :as => "cancel", :action => "cancel"
        end
      end
    end

    resources :schedules, :path => 'reservas' do
      collection do
        post "importar", :as => "import", :action => "import"
      end
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :disciplines, :path => "disciplinas" do
        collection do
          post "importar", :as => "import", :action => "import"
        end
      end
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :classrooms, :path => "salas" do
        collection do
          post "importar", :as => "import", :action => "import"
        end
      end
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :categories, :path => "categorias"
    end
    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :klasses, :path => "turmas" do
        collection do
            post "importar", :as => "import", :action => "import"
        end
      end
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :periods, :path => "periodos"
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :materiels, :path => "equipamentos"
    end

    resources :dashboards
    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :roles, :path => "perfils"
    end

    scope(:path_names => { :new => "cadastrar", :edit => "editar" }) do
      resources :sectors, :path => "setores"
    end

  end
  resources :schedules, :path => "reservas"
  resources :welcome
  devise_for :users, :path => "usuarios"
  authenticated :user do
    root :to => redirect('acesso/reservas')
  end
  root 'welcome#index'
end

app/controllers/management/categories_controller.rb
class Management::CategoriesController < ApplicationController
  before_action :authenticate_user!, :set_session, :get_current_user, :get_permissions_from_user, :authorize
  before_action :set_category, only: [:show, :update, :destroy, :edit]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(:page => params[:page], per_page:30)
    @number = Category.count

    respond_to do |format|
      format.html
      format.json { render json: Category.all }
    end
  end

  # POST /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1.json
  def show
    respond_to do |format|
      format.json { render json: @category }
    end
  end

  # GET /categories/edit/1
  def edit
  end

  # POST /categories
  # PODT /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to management_categories_path }
        format.json { render json:  @category, status: :created }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to management_categories_path }
        format.json { render json: @category, status: :ok }
      else
        format.html { render :edit }
        format.json { render json:  @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to management_categories_url, notice: 'Category was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def set_session
    @session = 6
  end
end

app/controllers/management/classrooms_controller.rb
class Management::ClassroomsController < ApplicationController
  before_action :authenticate_user!, :set_session, :get_current_user, :get_permissions_from_user, :authorize
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.paginate(:page => params[:page], per_page: 30)
    @number = Classroom.count

    respond_to do |format|
      format.html
      format.json { render :json => Classroom.all.to_json(include: :category) }
    end
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1.json
  def show
    respond_to do |format|
      format.json { render :json =>  @classroom.to_json(include: :category) }
    end
  end

  # GET /classrooms/edit/1
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.state = @classroom.state ? true : false
    respond_to do |format|
      if @classroom.save
        format.html { redirect_to management_classrooms_path }
        format.json { render :json =>  @classroom.to_json(include: :category), status: :created }
      else
        puts "format #{format}"
        # render new, buy change the url
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    @classroom.state = @classroom.state ? false : true
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to management_classrooms_path }
        format.json { render :json => @classroom.to_json(include: :category), status: :created }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to management_classroom_url, notice: 'Classroom was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def import
    @array = Classroom.import(params[:file], params[:category_id])
    if @array[0]
      redirect_to new_management_classroom_path, :flash => { :error => @array[1] }
    else
      redirect_to management_classrooms_path
    end
  end

  private
  def set_room
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:capacity, :room, :building, :category_id, :state, :description, :responsible_person)
  end

  def set_session
    @session = 7
  end
end

app/controllers/management/departments_controller.rb
class Management::DepartmentsController < ApplicationController
  before_action :authenticate_user!, :set_session, :get_current_user, :get_permissions_from_user, :authorize
  before_action :set_department, only: [:show, :update, :destroy, :edit]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.paginate(:page => params[:page], per_page: 30)
    @number = Department.count
    respond_to do |format|
      format.html
      format.json { render json: Department.all }
    end
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1.json
  def show
    respond_to do |format|
      format.json { render json: @department }
    end
  end

  # GET /departments/edit/1
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to management_departments_path }
        format.json { render json:  @department, status: :created}
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to management_departments_path }
        format.json { render json: @department, status: :ok }
      else
        format.html { render :edit }
        format.json { render json:  @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to management_departments_url, notice: 'Department was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name, :abbreviation, :code, :sector_id)
  end

  def set_session
    @session = 5
  end
end

app/controllers/management/disciplines_controller.rb
class Management::DisciplinesController < ApplicationController
  before_action :authenticate_user!, :set_session, :get_current_user, :get_permissions_from_user, :authorize
  before_action :set_discipline, only: [:update, :destroy, :edit, :show]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.paginate(:page => params[:page], per_page: 30)
    @number = Discipline.count
    respond_to do |format|
      format.html
      format.json { render :json => Discipline.all.to_json(include: :department) }
    end
  end

  # GET /disciplines/1.json
  def show
    respond_to do |format|
      format.json { render :json => @discipline.to_json(include: :department) }
    end
  end

  # POST /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/edit/1
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)
    respond_to do |format|
      if @discipline.save
        format.html { redirect_to management_disciplines_path }
        format.json { render :json => @discipline.to_json(include: :department), status: :created }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to management_disciplines_path }
        format.json { render :json => @discipline.to_json(include: :department), status: :created }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to management_disciplines_path, notice: 'Discipline was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def import
    # pegar total de registros e fazer um progress bar
    @array = Discipline.import(params[:file], params[:department_id])
    if @array[0]
      redirect_to new_management_discipline_path, :flash => { :error => @array[1] }
    else
      redirect_to management_disciplines_path
    end
  end

  private
  def set_discipline
    @discipline = Discipline.find(params[:id])
  end

  def discipline_params
    params.require(:discipline).permit(:name, :discipline_code, :department_id)
  end

  def set_session
    @session = 8
  end
end

app/controllers/management/events_controller.rb
class Management::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params.has_key?(:classroom)
      @events = Event.where(start: params[:start]..params[:end], classroom_id: params[:classroom])
    else
      @events = Event.where(start: params[:start]..params[:end])
    end
    @classrooms = Classroom.where(state: true)
    respond_to do |format|
      format.html
      format.json { render json: @events }
      # format.json { render :json => {
      #                         :events => @event,
      #                         :classrooms => @classrooms } }
    end
    # @events = Event.where(start: params[:start]..params[:end])
    # puts @events.count
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.json { render json: @event.to_json(:include => [:classroom, :user, :klass, :discipline]) }
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      puts params[:id]
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start, :end, :reservation, :title, :frequency, :state, :klass_id, :discipline_id, :classroom_id, :user_id)
    end
end

app/controllers/management/materiels_controller.rb
class Management::MaterielsController < ApplicationController
  before_action :authenticate_user!, :set_session, :get_current_user, :get_permissions_from_user, :authorize
  before_action :set_materiel, only: [:show, :edit, :update, :destroy]

  # GET /equipments
  # GET /equipments.json
  def index
    @materiels = Materiel.paginate(:page => params[:page], per_page: 30)
    @number = Materiel.count

    respond_to do |format|
      format.html
      format.json { render :json => Materiel.all.to_json(include: :room) }
    end
  end

  # GET /equipments/new
  def new
    @materiel = Materiel.new
  end

  # GET /equipments/1.json
  def show
    respond_to do |format|
      format.json { render json: @materiel }
    end
  end

  # GET /equipments/edit/1
  def edit
  end

  # POST /equipments
  # POST /equipments.json
  def create
    @materiel = Materiel.new(materiel_params)
    respond_to do |format|
      if @materiel.save
        format.html { redirect_to management_materiels_path }
        format.json { render :json => @materiel.to_json(include: :room), status: :created }
      else
        format.html { render :new }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipments/1
  # PATCH/PUT /equipments/1.json
  def update
    respond_to do |format|
      if @materiel.update(materiel_params)
        format.html { redirect_to management_materiels_path }
        format.json { render :json => @materiel.to_json(include: :room), status: :ok }
      else
        format.html { render :edit }
        format.json { render json:  @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipments/1
  # DELETE /equipments/1.json
  def destroy
    @materiel.destroy
    respond_to do |format|
      format.html { redirect_to management_materiels_url, notice: 'Equipment was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_materiel
    @materiel = Materiel.find(params[:id])
  end

  def materiel_params
    params.require(:materiel).permit(:name, :patrimony, :serial_number, :classroom_id)
  end

  def set_session
    @session = 10
  end
end

app/helpers/management/categories_helper.rb
module Management::CategoriesHelper
end

app/helpers/management/classrooms_helper.rb
module Management::ClassroomsHelper
end

app/helpers/management/departments_helper.rb
module Management::DepartmentsHelper
end

app/helpers/management/disciplines_helper.rb
module Management::DisciplinesHelper
end

app/helpers/management/klasses_helper.rb
module Management::KlassesHelper
end

app/helpers/management/materiels_helper.rb
module Management::MaterielsHelper
end

app/views/management/solicitations/_form.html.erb
<% states = ['Aguardando aprovação', 'Aprovado', 'Recusado', 'Cancelado'] %>
<div class="row">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-body">
                <%= form_for([:management, @solicitation], :html => {class: 'form-horizontal'}) do |f| %>
                <div class="form-group">
                    <div class="col-md-12">
                        <div style="border-bottom: 2px solid #ddd;">
                                <h3><i class="fa fa-eye"></i> Reserva</h3>
                        </div>
                    </div>
                </div>
                <% if @solicitation.klass_id.nil? && @solicitation.discipline_id.nil? %>
                  <div class="form-group" style="padding-top: 10px">
                      <%= f.label :title, 'Descrição', class: 'control-label col-sm-3' %>
                      <div class="col-sm-7">
                          <%= f.text_field :title, class: 'form-control', placeholder: 'Festa da Ana', autofocus: true, disabled: true %>
                      </div>
                  </div>
                <% else %>
                  <div class="form-group" style="padding-top: 10px">
                      <%= f.label :title, 'Descrição', class: 'control-label col-sm-3' %>
                      <div class="col-sm-7">
                          <%= f.text_field :title, class: 'form-control', placeholder: 'Festa da Ana', autofocus: true, disabled: true, :value => "#{@solicitation.klass.name} - #{@solicitation.discipline.discipline_code} #{@solicitation.discipline.name}" %>
                      </div>
                  </div>
                <% end %>
                <%= f.fields_for :user do |user_form| %>
                  <div class="form-group" style="padding-top: 10px">
                      <%= user_form.label :name, 'Solicitante', class: 'control-label col-sm-3' %>
                      <div class="col-sm-7">
                          <%= user_form.text_field :name, class: 'form-control', placeholder: '21/07/2017', autofocus: true, disabled: true %>
                      </div>
                  </div>
                <% end %>
                <div class="form-group" style="padding-top: 10px">
                    <%= f.label :start, 'Início', class: 'control-label col-sm-3' %>
                    <div class="col-sm-7">
                        <%= f.text_field :start, class: 'form-control', placeholder: '21/07/2017', :value => @solicitation.start.strftime('%d/%m/%Y %H:%M'), autofocus: true, disabled: true %>
                    </div>
                </div>
                <div class="form-group" style="padding-top: 10px">
                    <%= f.label :end, 'Fim', class: 'control-label col-sm-3' %>
                    <div class="col-sm-7">
                        <%= f.text_field :end, class: 'form-control', placeholder: '21/07/2017', :value => @solicitation.end.strftime('%d/%m/%Y %H:%M'), autofocus: true, disabled: true %>
                    </div>
                </div>
                <%= f.fields_for :classroom do |classroom_form| %>
                  <div class="form-group" style="padding-top: 10px">
                      <%= classroom_form.label :room, 'Sala', class: 'control-label col-sm-3' %>
                      <div class="col-sm-7">
                          <%= classroom_form.text_field :room, class: 'form-control', placeholder: '21/07/2017', autofocus: true, disabled: true %>
                      </div>
                  </div>
                <% end %>
                <div class="form-group" style="padding-top: 10px">
                    <%= f.label :state, 'Status', class: 'control-label col-sm-3' %>
                    <div class="col-sm-7">
                        <%= f.text_field :state, class: 'form-control', placeholder: '21/07/2017', autofocus: true, disabled: true, value: get_state(@solicitation.state) %>
                    </div>
                </div>
                <div class="form-group pull">
                    <div class="col-sm-offset-3 col-sm-7">
                        <div class="pull-right">
                          <% if can(:edit, :solicitation) && (@currentUser.id == 1 || @currentUser.id == 2)  %>
                            <% case @solicitation.state %>
                              <% when 1 %>
                                <%= link_to '<i class=""></i> Aprovar'.html_safe, approve_management_solicitations_path(@solicitation), method: :put,
                                data: {confirm: 'Are you sure?'},  :class => 'btn btn-success' %>
                                <%= link_to '<i class=""></i> Recusar'.html_safe, refuse_management_solicitations_path(@solicitation), method: :put,
                                data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
                              <% when 2 %>
                                <%= link_to '<i class=""></i> Cancelar'.html_safe, cancel_management_solicitations_path(@solicitation), method: :put,
                                data: {confirm: 'Are you sure?'}, :class => 'btn btn-warning' %>
                            <% end %>
                          <% elsif @solicitation.state == 1 || @solicitation.state == 2 %>
                            <%= link_to '<i class=""></i> Cancelar'.html_safe, cancel_management_solicitations_path(@solicitation), method: :put,
                            data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
                          <% end %>
                          <%= link_to 'Voltar', management_solicitations_path, class: 'btn btn-dark-blue' %>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/management/solicitations/edit.html.erb
<%= render :partial => 'layouts/sidenav', :locals => {:active => 1} %>
<div class="main-content">
    <div class="row">
        <ol class="breadcrumb">
          <li>
            <%= link_to '<i class="fa fa-calendar"></i> Reservas'.html_safe, management_schedules_path %>
          </li>
          <li><%= link_to '<i class="fa fa-bell"></i> Solicitações'.html_safe, management_solicitations_path %></li>
          <li><i class="fa fa-eye"></i> Visualizar reserva</li>
        </ol>
    </div>
    <div class="form">
        <%= render 'form' %>
    </div>
</div>

app/views/management/solicitations/index.html.erb
<%= render :partial => 'layouts/sidenav', :locals => {:active => 1} %>
<%
=begin
  Ao invés de fazer um switch case para verificar qual o valor do atributo 'state' da tabela schedule,
  é usado um array 'states', onde cada posição vai representar o valor do atributo 'state' - 1
=end
  states = ['Aguardando aprovação', 'Aprovado', 'Recusado', 'Cancelado']
%>
<div class="main-content">
  <div class="row">
    <ol class="breadcrumb">
      <li>
        <%= link_to '<i class="fa fa-calendar"></i> Reservas'.html_safe, management_schedules_path %>
      </li>
      <li><i class="fa fa-bell"></i> Solicitações</li>
    </ol>
  </div>

  <%= render :partial => 'layouts/flash_notice' %>

  <div class="row" style="margin-top:15px;">
    <div class="col-md-10">
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-6">
              <h3 class="panel-title">Solicitações</h3>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <input type="text" id="search" name="search" placeholder="Buscar por solicitações ..." autofocus>
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-list" id="table">
              <tr>
                <th>Solicitante</th>
                <th>Data início</th>
                <th>Data fim</th>
                <th>Status</th>
                <th style="width: 150px"><i class="fa fa-cog"></i></th>
              </tr>
              <% @solicitations.each do |s| %>
                <% if s.state == 1 %>
                  <tr class="pendente">
                <% else %>
                  <tr>
                <% end %>
                  <% if s.user.nil? %>
                    <td></td>
                  <% else %>
                    <td><%= s.user.name %></td>
                  <% end %>
                  <td><%= s.start.strftime('%d/%m/%Y %H:%M') %></td>
                  <td><%= s.end.strftime('%d/%m/%Y %H:%M') %></td>
                  <td><%= states[s.state-1] %></td>
                  <td>
                    <%= link_to '<i class="fa fa-eye"></i>'.html_safe, edit_management_solicitation_path(s),  :class => 'btn btn-info', title: 'Visualizar solicitação', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' %>
                    <% if can(:edit, :solicitation) && (@currentUser.id == 1 || @currentUser.id == 2)  %>
                      <% case s.state %>
                        <% when 1 %>
                          <%= link_to '<i class="fa fa-play"></i>'.html_safe, approve_management_solicitations_path(s), method: :put,
                          data: {confirm: 'Are you sure?'},  :class => 'btn btn-success', title: 'Aprovar', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' %>
                          <%= link_to '<i class="fa fa-remove"></i>'.html_safe, refuse_management_solicitations_path(s), method: :put,
                          data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger', title: 'Recusar', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' %>
                        <% when 2 %>
                          <%= link_to '<i class="fa fa-trash"></i>'.html_safe, cancel_management_solicitations_path(s), method: :put,
                          data: {confirm: 'Are you sure?'}, :class => 'btn btn-warning', title: 'Cancelar', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' %>
                      <% end %>
                    <% elsif s.state == 1 || s.state == 2 %>
                      <%= link_to '<i class="fa fa-trash"></i>'.html_safe, cancel_management_solicitations_path(s), method: :put,
                      data: {confirm: 'Are you sure?'}, :class => 'btn btn-warning', title: 'Cancelar', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="hidden-xs col-sm-4" style="padding: 16px">
              <% if @number == 1 %>
              Total de <%= @number %> registro
              <% else %>
              Total de <%= @number %> registros
              <% end %>
            </div>
            <div class="col-sm-8">
              <div class="pull-right">
                <%= will_paginate @solicitations, renderer: BootstrapPagination::Rails, :previous_label => '<i class="fa fa-long-arrow-left"></i>', :next_label => '<i class="fa fa-long-arrow-right"></i>' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>